[".config/nvim"]
	type = "git-repo"
	url = "git@github.com:muratoffalex/nvim.git"
	refreshPeriod = "1h"

# various images - wallpapers, etc.
["images"]
	type = "git-repo"
	url = "git@github.com:muratoffalex/images.git"
	refreshPeriod = "168h"
