import = ["~/.config/alacritty/themes/tokyonight-day.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 15

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[window]
startup_mode = "Windowed"
decorations = "Buttonless"
dynamic_padding = false
# only for mac
option_as_alt = "OnlyLeft"

[window.padding]
x = 6
y = 6

[window.dimensions]
columns = 90
lines = 30

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[keyboard]
bindings = [
  # open t - tmux smart session manager <Ctrl-a>T
  { key = "J", mods = "Command", chars = "\u0001\u0054" },
  { key = "Key0",     mods = "Command", action = "ResetFontSize"    },
  { key = "Plus",   mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Command", action = "DecreaseFontSize" }
]
