[general]
import = ["~/.config/alacritty/themes/tokyonight-day.toml"]
live_config_reload = true

[terminal.shell]
args = ["-l", "-c", "session_manager"]
program = "/usr/local/bin/fish"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
# comfortable for fhd (14 inch), qhd
size = 20

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight"
[font.bold]
style = "SemiBold"
[font.italic]
style = "SemiLight Italic"
[font.bold_italic]
style = "SemiBold Italic"

[window]
startup_mode = "Windowed"
decorations = "Buttonless"
dynamic_padding = false
# only for mac
option_as_alt = "OnlyLeft"

[window.padding]
x = 4
y = 3

[window.dimensions]
columns = 90
lines = 30

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[keyboard]
bindings = [
	# open default tmux session list <Ctrl-a>T
  { key = "J", mods = "Command", chars = "\u0001\u0054" },
  # open last session <Ctrl-a>L
  { key = "L", mods = "Command", chars = "\u0001\u004c" },
  # open sesh fzf <Ctrl-a>K
  { key = "K", mods = "Command", chars = "\u0001\u004b" },
  { key = "Key0",     mods = "Command", action = "ResetFontSize"    },
  { key = "Plus",   mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Command", action = "DecreaseFontSize" }
]
